drop table users;
create table users
(
    user INTEGER,
    gender VARCHAR(6),
    age INTEGER,
    working_status VARCHAR(1024),
    region VARCHAR(60),
    music VARCHAR(1024),
    list_own INTEGER,
    list_back INTEGER,
    q_a INTEGER,
    q_b INTEGER,
    q_c INTEGER,
    q_d INTEGER,
    q_e INTEGER,
    q_f INTEGER,
    q_g INTEGER,
    q_h INTEGER,
    q_i INTEGER,
    q_j INTEGER,
    q_k INTEGER,
    q_l INTEGER,
    q_m INTEGER,
    q_n INTEGER,
    q_o INTEGER,
    q_p INTEGER,
    q_q INTEGER,
    q_r INTEGER,
    q_s INTEGER
);
